param(
  [ValidateSet("api","web")]
  [string]$Service = "web"
)

$jsonPath = Join-Path $PSScriptRoot "..\..\railway.json"
$lockPath = Join-Path $PSScriptRoot "..\.deploy.lock"
$ignorePath = Join-Path $PSScriptRoot "..\..\.railwayignore"

# Prevent concurrent deploys from racing on railway.json (documented incident 2026-05-19).
if (Test-Path $lockPath) {
  $lockAge = (Get-Date) - (Get-Item $lockPath).LastWriteTime
  if ($lockAge.TotalMinutes -lt 30) {
    Write-Error "Deploy lock exists ($lockPath, age=$($lockAge.TotalMinutes.ToString('F0'))min). Another deploy may be in progress. Remove the lock file manually if this is stale."
    exit 1
  }
  Write-Warning "Stale deploy lock found ($($lockAge.TotalMinutes.ToString('F0'))min old), removing."
  Remove-Item $lockPath -Force
}
New-Item -ItemType File -Path $lockPath -Force | Out-Null

$original = Get-Content -LiteralPath $jsonPath -Raw
$dockerfile = if ($Service -eq "web") { "wcore-web/apps/web/Dockerfile.railway" } else { "wcore-web/apps/api/Dockerfile.railway" }

# The archive uploaded by `railway up` IS the Docker build context. Shipping paths that
# the selected Dockerfile never COPYs wasted 15x the bytes and made the upload exceed the
# CLI request timeout on a slow uplink (incident 2026-08-02, ~0.8 Mbps up, 31.6 MiB sent
# for a 2 MiB API context). Keep these lists in sync with the two Dockerfile.railway files.
$ignoreLines = @(
  "# Auto-generated by deploy.ps1 for service '$Service'. Removed after the deploy.",
  "docs/",
  ".github/",
  "wcore-web/docs/",
  "wcore-web/contracts/",
  "wcore-web/e2e/",
  "wcore-gsheet/src/",
  "wcore-gsheet/docs/",
  "wcore-gsheet/pulls/",
  "wcore-gsheet/railway-relay/"
)
if ($Service -eq "api") {
  # apps/web is 24 MiB of public assets and is never COPYd by the API Dockerfile.
  $ignoreLines += "wcore-web/apps/web/"
} else {
  $ignoreLines += "wcore-web/apps/api/"
}

$hadIgnore = Test-Path -LiteralPath $ignorePath
$originalIgnore = if ($hadIgnore) { Get-Content -LiteralPath $ignorePath -Raw } else { $null }

$deployExitCode = 0
try {
  $updated = $original -replace '"dockerfilePath":\s*"[^"]*"', """dockerfilePath"": ""$dockerfile"""
  Set-Content -LiteralPath $jsonPath -Value $updated -NoNewline
  Set-Content -LiteralPath $ignorePath -Value ($ignoreLines -join "`n") -NoNewline

  railway up (Join-Path $PSScriptRoot "..\..") --path-as-root --service $Service --ci
  $deployExitCode = $LASTEXITCODE
} finally {
  Set-Content -LiteralPath $jsonPath -Value $original -NoNewline
  if ($hadIgnore) {
    Set-Content -LiteralPath $ignorePath -Value $originalIgnore -NoNewline
  } else {
    Remove-Item -LiteralPath $ignorePath -Force -ErrorAction SilentlyContinue
  }
  Remove-Item $lockPath -Force -ErrorAction SilentlyContinue
}
if ($deployExitCode -ne 0) { exit $deployExitCode }
