#!/usr/bin/env node
// Build the merged chains/index.ts that re-exports from @wcore/chains + local web-only chains.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CHAINS_DIR = __dirname;
const GSHEET_DIST = resolve(__dirname, "..", "..", "..", "..", "..", "wcore-gsheet", "dist", "chains");

const gsheetChains = readdirSync(GSHEET_DIST)
  .filter((f) => f.endsWith(".ts") && f !== "types.ts" && f !== "index.ts")
  .map((f) => f.replace(/\.ts$/, ""));

const localFiles = readdirSync(CHAINS_DIR)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts" && f !== "chains.test.ts")
  .map((f) => f.replace(/\.ts$/, ""));

const localUnique = localFiles.filter((n) => !gsheetChains.includes(n)).sort();

const lines = [];
lines.push(`// Auto-generated by tools/build-chains-index.mjs. Do not edit by hand.`);
lines.push(`// Source: @wcore/chains (113 chains from wcore-gsheet/dist) + ${localUnique.length} local web-only chains.`);
lines.push(`// Re-run: node tools/build-chains-index.mjs`);
lines.push(``);
lines.push(`import {`);
lines.push(`  chains as gsheetChains,`);
lines.push(`  chainList as gsheetChainList,`);
lines.push(`  type ChainConfig,`);
lines.push(`  type ChainKey as GsheetChainKey,`);
lines.push(`  type VmType,`);
lines.push(`} from "@wcore/chains";`);
lines.push(``);
lines.push(`// Local web-only chains (not yet ported to wcore-gsheet/src/*.gs).`);
for (const name of localUnique) {
  lines.push(`import { ${name} } from "./${name}.js";`);
}
lines.push(``);
lines.push(`export const chains = {`);
lines.push(`  ...gsheetChains,`);
for (const name of localUnique) {
  lines.push(`  ${name},`);
}
lines.push(`} as const;`);
lines.push(``);
lines.push(`export type ChainKey = keyof typeof chains;`);
lines.push(``);
lines.push(`export const chainList: readonly ChainConfig[] = Object.values(chains);`);
lines.push(``);
lines.push(`export function getChain(key: string): ChainConfig | undefined {`);
lines.push(`  return (chains as Record<string, ChainConfig>)[key];`);
lines.push(`}`);

const out = lines.join("\n") + "\n";
const outPath = resolve(CHAINS_DIR, "index.ts");
writeFileSync(outPath, out);
console.log(`[build-chains-index] wrote ${outPath} (${localUnique.length} local + 113 gsheet = ${113 + localUnique.length} total)`);
