// Auto-generated by tools/build-chains-index.mjs. Do not edit by hand.
// Source: @wcore/chains (183 chains from wcore-gsheet/dist) + 0 local web-only chains.
// Re-run: node tools/build-chains-index.mjs

import {
  chains as gsheetChains,
  chainList as gsheetChainList,
  type ChainKey as GsheetChainKey,
} from "@wcore/chains";
import type { ChainConfig, VmType } from "@wcore/chains/types";

// Local web-only chains (not yet ported to wcore-gsheet/src/*.gs).

export const chains = {
  ...gsheetChains,
} as const;

export type ChainKey = keyof typeof chains;

export const chainList: readonly ChainConfig[] = Object.values(chains);

export function getChain(key: string): ChainConfig | undefined {
  return (chains as Record<string, ChainConfig>)[key];
}
