// Auto-generated by tools/build-chains-index.mjs. Do not edit by hand.
// Source: @wcore/chains (113 chains from wcore-gsheet/dist) + 69 local web-only chains.
// Re-run: node tools/build-chains-index.mjs

import {
  chains as gsheetChains,
  chainList as gsheetChainList,
  type ChainConfig,
  type ChainKey as GsheetChainKey,
  type VmType,
} from "@wcore/chains";

// Local web-only chains (not yet ported to wcore-gsheet/src/*.gs).
import { AEVO } from "./AEVO.js";
import { AIRDAO } from "./AIRDAO.js";
import { ARENA_Z } from "./ARENA_Z.js";
import { AVES_NETWORK } from "./AVES_NETWORK.js";
import { AWAJI } from "./AWAJI.js";
import { BXN } from "./BXN.js";
import { CELESTIA } from "./CELESTIA.js";
import { CREDITCOIN } from "./CREDITCOIN.js";
import { CROSSBELL } from "./CROSSBELL.js";
import { CROSS_MAINNET } from "./CROSS_MAINNET.js";
import { CYSIC } from "./CYSIC.js";
import { DOGECHAIN } from "./DOGECHAIN.js";
import { DOS_CHAIN } from "./DOS_CHAIN.js";
import { DYDX } from "./DYDX.js";
import { EDEN } from "./EDEN.js";
import { EDGELESS } from "./EDGELESS.js";
import { EDU_CHAIN } from "./EDU_CHAIN.js";
import { ENDURANCE } from "./ENDURANCE.js";
import { ETHEREUM_CLASSIC } from "./ETHEREUM_CLASSIC.js";
import { ETHO_PROTOCOL } from "./ETHO_PROTOCOL.js";
import { FANTOM } from "./FANTOM.js";
import { FORMA } from "./FORMA.js";
import { FVM } from "./FVM.js";
import { GENSYN } from "./GENSYN.js";
import { HARMONY } from "./HARMONY.js";
import { HAVEN1 } from "./HAVEN1.js";
import { HORIZEN_EON } from "./HORIZEN_EON.js";
import { HYCHAIN } from "./HYCHAIN.js";
import { ICB_NETWORK } from "./ICB_NETWORK.js";
import { INEVM } from "./INEVM.js";
import { IOTA_EVM } from "./IOTA_EVM.js";
import { KAVA } from "./KAVA.js";
import { KITEAI } from "./KITEAI.js";
import { LAYERAI } from "./LAYERAI.js";
import { LIGHTLINK } from "./LIGHTLINK.js";
import { LORENZO } from "./LORENZO.js";
import { LUMIO } from "./LUMIO.js";
import { MIND } from "./MIND.js";
import { MOCA_CHAIN } from "./MOCA_CHAIN.js";
import { MOONCHAIN } from "./MOONCHAIN.js";
import { NEON } from "./NEON.js";
import { NEO_X } from "./NEO_X.js";
import { NEUTRON } from "./NEUTRON.js";
import { NEXI_CHAIN } from "./NEXI_CHAIN.js";
import { NEXUS } from "./NEXUS.js";
import { NOBLE } from "./NOBLE.js";
import { NUMINE } from "./NUMINE.js";
import { PLAYNANCE_PLAYBLOCK } from "./PLAYNANCE_PLAYBLOCK.js";
import { PROOF_OF_PLAY_APEX } from "./PROOF_OF_PLAY_APEX.js";
import { REDSTONE } from "./REDSTONE.js";
import { REI_NETWORK } from "./REI_NETWORK.js";
import { RIVALZ } from "./RIVALZ.js";
import { ROLLUX } from "./ROLLUX.js";
import { RSS3 } from "./RSS3.js";
import { SHIDO_NETWORK } from "./SHIDO_NETWORK.js";
import { SHIMMER_EVM } from "./SHIMMER_EVM.js";
import { SKALE } from "./SKALE.js";
import { STACK } from "./STACK.js";
import { STARGAZE } from "./STARGAZE.js";
import { STEP_NETWORK } from "./STEP_NETWORK.js";
import { STRIDE } from "./STRIDE.js";
import { SURFLAYER } from "./SURFLAYER.js";
import { TANGLE } from "./TANGLE.js";
import { TARAXA } from "./TARAXA.js";
import { TON } from "./TON.js";
import { WORLD_MOBILE } from "./WORLD_MOBILE.js";
import { ZERO } from "./ZERO.js";
import { ZILLIQA_EVM } from "./ZILLIQA_EVM.js";
import { ZKFAIR } from "./ZKFAIR.js";

export const chains = {
  ...gsheetChains,
  AEVO,
  AIRDAO,
  ARENA_Z,
  AVES_NETWORK,
  AWAJI,
  BXN,
  CELESTIA,
  CREDITCOIN,
  CROSSBELL,
  CROSS_MAINNET,
  CYSIC,
  DOGECHAIN,
  DOS_CHAIN,
  DYDX,
  EDEN,
  EDGELESS,
  EDU_CHAIN,
  ENDURANCE,
  ETHEREUM_CLASSIC,
  ETHO_PROTOCOL,
  FANTOM,
  FORMA,
  FVM,
  GENSYN,
  HARMONY,
  HAVEN1,
  HORIZEN_EON,
  HYCHAIN,
  ICB_NETWORK,
  INEVM,
  IOTA_EVM,
  KAVA,
  KITEAI,
  LAYERAI,
  LIGHTLINK,
  LORENZO,
  LUMIO,
  MIND,
  MOCA_CHAIN,
  MOONCHAIN,
  NEON,
  NEO_X,
  NEUTRON,
  NEXI_CHAIN,
  NEXUS,
  NOBLE,
  NUMINE,
  PLAYNANCE_PLAYBLOCK,
  PROOF_OF_PLAY_APEX,
  REDSTONE,
  REI_NETWORK,
  RIVALZ,
  ROLLUX,
  RSS3,
  SHIDO_NETWORK,
  SHIMMER_EVM,
  SKALE,
  STACK,
  STARGAZE,
  STEP_NETWORK,
  STRIDE,
  SURFLAYER,
  TANGLE,
  TARAXA,
  TON,
  WORLD_MOBILE,
  ZERO,
  ZILLIQA_EVM,
  ZKFAIR,
} as const;

export type ChainKey = keyof typeof chains;

export const chainList: readonly ChainConfig[] = Object.values(chains);

export function getChain(key: string): ChainConfig | undefined {
  return (chains as Record<string, ChainConfig>)[key];
}
