import { getActiveFactoryChains, getFactoryAddress } from "@wcore/shared";

export interface GmChain {
  key: string;
  name: string;
}

const GM_CHAIN_NAMES: Record<string, string> = {
  ethereum: "Ethereum", base: "Base", arbitrum_one: "Arbitrum One",
  optimism: "Optimism", polygon: "Polygon", bsc: "BNB Chain",
  avalanche: "Avalanche", gnosis: "Gnosis", soneium: "Soneium",
  zksync_era: "zkSync Era", scroll: "Scroll", linea: "Linea",
  mantle: "Mantle", blast: "Blast", celo: "Celo", fraxtal: "Fraxtal",
  worldchain: "World Chain", unichain: "Unichain", berachain: "Berachain",
  ink: "Ink", abstract: "Abstract",
  polygon_zkevm: "Polygon zkEVM", zora: "Zora", mode: "Mode",
  sei: "Sei", superseed: "Superseed", shape: "Shape",
  ancient8: "Ancient8", bob: "BOB", lisk: "Lisk",
  metal_l2: "Metal L2",   redstone: "Redstone", robinhood_chain: "Robinhood Chain", appchain: "AppChain",
  camp: "Camp", duckchain: "DuckChain", cyber: "Cyber",
  rari: "RARI Chain", zircuit: "Zircuit", openledger: "OpenLedger",
  stable: "Stable", tac: "TAC", mitosis: "Mitosis", b3: "B3", sonic: "Sonic", citrea: "Citrea", cronos: "Cronos", fuse: "Fuse", kaia: "Kaia",
  moonbeam: "Moonbeam",
  moonriver: "Moonriver",
  astar: "Astar",
  aurora: "Aurora",
  metis: "Metis",
  boba: "Boba",
  pulsechain: "PulseChain",
  kcc: "KCC Mainnet",
  core: "Core",
  flare: "Flare",
  x_layer: "X Layer",
  shibarium: "Shibarium",
  degen: "Degen",
  beam: "Beam",
  ronin: "Ronin",
  opbnb: "opBNB",
  gravity: "Gravity",
  merlin: "Merlin",
  manta_pacific: "Manta Pacific",
  taiko_alethia: "Taiko Alethia",
  plasma: "Plasma",
  hashkey: "HashKey",
  hemi: "Hemi",
  hyperevm: "HyperEVM",
  immutable: "Immutable zkEVM",
  morph: "Morph",
  mezo: "Mezo",
  reya: "Reya Network",
  swellchain: "Swell Chain",
  swan: "Swan",
  vana: "Vana",
  story: "Story",
  intuition: "Intuition",
  plume: "Plume",
  superposition: "Superposition",
  monad: "Monad",
  megaeth: "MegaETH",
  doma: "Doma",
  b2: "B2",
  katana: "Katana",
};

const SOON_CHAIN_CANDIDATES: GmChain[] = [
  { key: "arbitrum_nova", name: "Arbitrum Nova" },
  { key: "fogo", name: "Fogo" },
  { key: "moonbeam", name: "Moonbeam" },
  { key: "moonriver", name: "Moonriver" },
  { key: "astar", name: "Astar" },
  { key: "rootstock", name: "Rootstock" },
  { key: "kcc", name: "KCC" },
  { key: "xdc", name: "XDC Network" },
  { key: "conflux", name: "Conflux eSpace" },
  { key: "gravity", name: "Gravity" },
  { key: "merlin", name: "Merlin" },
  { key: "manta_pacific", name: "Manta Pacific" },
  { key: "taiko_alethia", name: "Taiko Alethia" },
  { key: "plasma", name: "Plasma" },
  { key: "hashkey", name: "HashKey" },
  { key: "hemi", name: "Hemi" },
  { key: "hyperevm", name: "HyperEVM" },
  { key: "immutable", name: "Immutable zkEVM" },
  { key: "morph", name: "Morph" },
  { key: "mezo", name: "Mezo" },
  { key: "reya", name: "Reya Network" },
  { key: "swellchain", name: "Swell Chain" },
  { key: "swan", name: "Swan" },
  { key: "vana", name: "Vana" },
  { key: "story", name: "Story" },
  { key: "intuition", name: "Intuition" },
  { key: "etherlink", name: "Etherlink" },
  { key: "plume", name: "Plume" },
  { key: "polynomial", name: "Polynomial" },
  { key: "superposition", name: "Superposition" },
  { key: "syndicate_commons", name: "Syndicate Commons" },
  { key: "somnia", name: "Somnia" },
  { key: "monad", name: "Monad" },
  { key: "megaeth", name: "MegaETH" },
  { key: "matchain", name: "Matchain" },
  { key: "race", name: "RACE" },
  { key: "doma", name: "Doma" },
  { key: "b2", name: "B2" },
  { key: "botanix", name: "Botanix" },
  { key: "codex", name: "Codex" },
  { key: "juchain", name: "JuChain Mainnet" },
  { key: "katana", name: "Katana" },
  { key: "lens", name: "Lens" },
  { key: "mind", name: "Mind Network" },
  { key: "og", name: "0G Mainnet" },
  { key: "zero", name: "ZERO Network" },
  { key: "zetachain", name: "ZetaChain" },
  { key: "zklinknova", name: "zkLink Nova" },
  { key: "dbk_chain", name: "DBK Chain" },
  { key: "geb", name: "GEB" },
  { key: "bitlayer", name: "Bitlayer" },
  { key: "corn", name: "Corn" },
  { key: "flow", name: "Flow EVM" },
];

export function getGmChains(): GmChain[] {
  return getActiveFactoryChains()
    .filter((key) => GM_CHAIN_NAMES[key])
    .map((key) => ({ key, name: GM_CHAIN_NAMES[key]! }));
}

export function getSoonChains(): GmChain[] {
  return SOON_CHAIN_CANDIDATES.filter((chain) => !getFactoryAddress(chain.key));
}
