// AUTO-GENERATED by scripts/extract-deploy-chain-data.mjs — do not edit by hand.
// Source: packages/core/src/chains/*.ts (built-time extract).
// Regenerate when chain data changes: npx tsx scripts/extract-deploy-chain-data.mjs

import type { AddEthereumChainParams } from "./chain-params";

/**
 * Inline chain params for `wallet_addEthereumChain` fallback when MetaMask
 * does not know the target chain. Duplicated from @wcore/core (per AGENTS.md gotcha:
 * do not import @wcore/core at runtime from web frontend).
 */
export const DEPLOY_CHAIN_PARAMS: Record<string, AddEthereumChainParams> = {
  BASE: {
    chainId: "0x2105",
    chainName: "Base",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://base.drpc.org", "https://mainnet.base.org", "https://base-mainnet.public.blastapi.io"],
  },
  ETHEREUM: {
    chainId: "0x1",
    chainName: "Ethereum",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://eth.drpc.org", "https://1rpc.io/eth", "https://gateway.tenderly.co/public/mainnet", "https://eth.merkle.io", "https://rpc.eth.gateway.fm"],
  },
  ARBITRUM_ONE: {
    chainId: "0xa4b1",
    chainName: "Arbitrum One",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://arb1.arbitrum.io/rpc", "https://1rpc.io/arb", "https://arbitrum.drpc.org"],
  },
  OPTIMISM: {
    chainId: "0xa",
    chainName: "Optimism",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.optimism.io", "https://1rpc.io/op", "https://optimism.drpc.org"],
  },
  POLYGON: {
    chainId: "0x89",
    chainName: "Polygon",
    nativeCurrency: { name: "POL", symbol: "POL", decimals: 18 },
    rpcUrls: ["https://polygon.drpc.org", "https://rpc.ankr.com/polygon", "https://polygon.publicnode.com", "https://polygon.meowrpc.com", "https://1rpc.io/matic"],
  },
  BSC: {
    chainId: "0x38",
    chainName: "BNB Chain",
    nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
    rpcUrls: ["https://bsc.drpc.org", "https://bsc-dataseed1.binance.org", "https://bsc-dataseed2.binance.org"],
  },
  AVALANCHE: {
    chainId: "0xa86a",
    chainName: "Avalanche",
    nativeCurrency: { name: "Avalanche", symbol: "AVAX", decimals: 18 },
    rpcUrls: ["https://api.avax.network/ext/bc/C/rpc", "https://avalanche.public-rpc.com", "https://avalanche.drpc.org"],
  },
  GNOSIS: {
    chainId: "0x64",
    chainName: "Gnosis",
    nativeCurrency: { name: "xDAI", symbol: "xDAI", decimals: 18 },
    rpcUrls: ["https://rpc.gnosischain.com", "https://gnosis.publicnode.com", "https://gnosis.drpc.org"],
  },
  ZKSYNC_ERA: {
    chainId: "0x144",
    chainName: "zkSync Era",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.era.zksync.io", "https://zksync.drpc.org", "https://1rpc.io/zksync2-era", "https://zksync-era.blockpi.network/v1/rpc/public"],
  },
  SCROLL: {
    chainId: "0x82750",
    chainName: "Scroll",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.scroll.io", "https://scroll.drpc.org", "https://1rpc.io/scroll", "https://scroll-mainnet.public.blastapi.io"],
  },
  LINEA: {
    chainId: "0xe708",
    chainName: "Linea",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://linea.drpc.org", "https://rpc.linea.build", "https://1rpc.io/linea"],
  },
  MANTLE: {
    chainId: "0x1388",
    chainName: "Mantle",
    nativeCurrency: { name: "Mantle", symbol: "MNT", decimals: 18 },
    rpcUrls: ["https://rpc.mantle.xyz", "https://1rpc.io/mantle", "https://mantle.drpc.org", "https://mantle-rpc.publicnode.com"],
  },
  BLAST: {
    chainId: "0x13e31",
    chainName: "Blast",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.blast.io", "https://blast.din.dev/rpc", "https://blastl2-mainnet.public.blastapi.io"],
  },
  SONIC: {
    chainId: "0x92",
    chainName: "Sonic",
    nativeCurrency: { name: "Sonic", symbol: "S", decimals: 18 },
    rpcUrls: ["https://rpc.soniclabs.com", "https://sonic-rpc.publicnode.com", "https://sonic.drpc.org"],
  },
  CELO: {
    chainId: "0xa4ec",
    chainName: "Celo",
    nativeCurrency: { name: "Celo", symbol: "CELO", decimals: 18 },
    rpcUrls: ["https://forno.celo.org", "https://celo.drpc.org", "https://1rpc.io/celo", "https://celo-mainnet.public.blastapi.io"],
  },
  FRAXTAL: {
    chainId: "0xfc",
    chainName: "Fraxtal",
    nativeCurrency: { name: "Frax", symbol: "FRAX", decimals: 18 },
    rpcUrls: ["https://rpc.frax.com", "https://fraxtal.drpc.org", "https://fraxtal.gateway.tenderly.co"],
  },
  WORLDCHAIN: {
    chainId: "0x1e0",
    chainName: "World Chain",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://worldchain-mainnet.g.alchemy.com/public", "https://world-chain.drpc.org", "https://worldchain-mainnet.gateway.tenderly.co", "https://480.rpc.thirdweb.com"],
  },
  UNICHAIN: {
    chainId: "0x82",
    chainName: "Unichain",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.unichain.org", "https://unichain.drpc.org", "https://130.rpc.thirdweb.com"],
  },
  BERACHAIN: {
    chainId: "0x138de",
    chainName: "Berachain",
    nativeCurrency: { name: "Bera", symbol: "BERA", decimals: 18 },
    rpcUrls: ["https://rpc.berachain.com", "https://berachain.drpc.org", "https://berachain-rpc.publicnode.com"],
  },
  INK: {
    chainId: "0xdef1",
    chainName: "Ink",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc-gel.inkonchain.com", "https://ink.drpc.org", "https://rpc-qnd.inkonchain.com"],
  },
  ABSTRACT: {
    chainId: "0xab5",
    chainName: "Abstract",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://api.mainnet.abs.xyz", "https://abstract.drpc.org", "https://abstract.api.onfinality.io/public", "https://2741.rpc.thirdweb.com"],
  },
  SONEIUM: {
    chainId: "0x74c",
    chainName: "Soneium",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.soneium.org", "https://soneium.drpc.org"],
  },
  POLYGON_ZKEVM: {
    chainId: "0x44d",
    chainName: "Polygon zkEVM",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://zkevm-rpc.com", "https://polygon-zkevm.drpc.org", "https://1rpc.io/polygon/zkevm"],
  },
  ARBITRUM_NOVA: {
    chainId: "0xa4ba",
    chainName: "Arbitrum Nova",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://nova.arbitrum.io/rpc", "https://arbitrum-nova.drpc.org", "https://arbitrum-nova.publicnode.com"],
  },
  ZORA: {
    chainId: "0x76adf1",
    chainName: "Zora",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.zora.energy", "https://zora.drpc.org", "https://1rpc.io/zora", "https://rpc.ankr.com/zora", "https://zora-mainnet.public.blastapi.io", "https://7777777.rpc.thirdweb.com"],
  },
  MODE: {
    chainId: "0x868b",
    chainName: "Mode",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.mode.network", "https://mode.drpc.org", "https://1rpc.io/mode", "https://rpc.ankr.com/mode", "https://mode-mainnet.public.blastapi.io", "https://34443.rpc.thirdweb.com"],
  },
  SEI: {
    chainId: "0x531",
    chainName: "Sei",
    nativeCurrency: { name: "Sei", symbol: "SEI", decimals: 18 },
    rpcUrls: ["https://evm-rpc.sei-apis.com", "https://1329.rpc.thirdweb.com"],
  },
  SUPERSEED: {
    chainId: "0x14d2",
    chainName: "Superseed",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.superseed.xyz", "https://superseed.drpc.org"],
  },
  SHAPE: {
    chainId: "0x168",
    chainName: "Shape",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.shape.network", "https://shape-mainnet.g.alchemy.com/public", "https://360.rpc.thirdweb.com"],
  },
  ANCIENT8: {
    chainId: "0x34fb5e38",
    chainName: "Ancient8",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.ancient8.gg", "https://888888888.rpc.thirdweb.com"],
  },
  BOB: {
    chainId: "0xed88",
    chainName: "BOB",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.gobob.xyz/", "https://bob.drpc.org", "https://bob-mainnet.public.blastapi.io"],
  },
  LISK: {
    chainId: "0x46f",
    chainName: "Lisk",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.api.lisk.com", "https://lisk.drpc.org", "https://1135.rpc.thirdweb.com"],
  },
  METAL_L2: {
    chainId: "0x6d6",
    chainName: "Metal L2",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.metall2.com", "https://metall2.drpc.org"],
  },
  REDSTONE: {
    chainId: "0x2b2",
    chainName: "Redstone",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.redstonechain.com", "https://690.rpc.thirdweb.com"],
  },
  APPCHAIN: {
    chainId: "0x1d2",
    chainName: "AppChain",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.appchain.xyz", "https://466.rpc.thirdweb.com"],
  },
  CAMP: {
    chainId: "0x1e4",
    chainName: "Camp",
    nativeCurrency: { name: "Camp", symbol: "CAMP", decimals: 18 },
    rpcUrls: ["https://rpc.camp.raas.gelato.cloud", "https://484.rpc.thirdweb.com"],
  },
  DUCKCHAIN: {
    chainId: "0x15a9",
    chainName: "DuckChain",
    nativeCurrency: { name: "Toncoin", symbol: "TON", decimals: 18 },
    rpcUrls: ["https://rpc.duckchain.io", "https://rpc-hk.duckchain.io"],
  },
  CYBER: {
    chainId: "0x1d88",
    chainName: "Cyber",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://cyber.alt.technology", "https://rpc.cyber.co"],
  },
  RARI: {
    chainId: "0x52415249",
    chainName: "RARI Chain",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.rpc.rarichain.org/http", "https://1380012617.rpc.thirdweb.com"],
  },
  ZIRCUIT: {
    chainId: "0xbf04",
    chainName: "Zircuit",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.zircuit.com", "https://48900.rpc.thirdweb.com"],
  },
  OPENLEDGER: {
    chainId: "0x64c",
    chainName: "OpenLedger",
    nativeCurrency: { name: "OpenLedger", symbol: "OPEN", decimals: 18 },
    rpcUrls: ["https://rpc.openledger.xyz", "https://1612.rpc.thirdweb.com"],
  },
  STABLE: {
    chainId: "0x3dc",
    chainName: "Stable",
    nativeCurrency: { name: "gUSDT", symbol: "gUSDT", decimals: 18 },
    rpcUrls: ["https://rpc.stable.xyz"],
  },
  TAC: {
    chainId: "0xef",
    chainName: "TAC",
    nativeCurrency: { name: "TAC", symbol: "TAC", decimals: 18 },
    rpcUrls: ["https://rpc.tac.build", "https://rpc.ankr.com/tac", "https://tac.drpc.org", "https://239.rpc.thirdweb.com"],
  },
  MITOSIS: {
    chainId: "0x1e790",
    chainName: "Mitosis",
    nativeCurrency: { name: "MITO", symbol: "MITO", decimals: 18 },
    rpcUrls: ["https://rpc.mitosis.org"],
  },
  B3: {
    chainId: "0x208d",
    chainName: "B3",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet-rpc.b3.fun", "https://8333.rpc.thirdweb.com"],
  },
  CITREA: {
    chainId: "0x1012",
    chainName: "Citrea",
    nativeCurrency: { name: "Citrea Bitcoin", symbol: "cBTC", decimals: 18 },
    rpcUrls: ["https://rpc.mainnet.citrea.xyz"],
  },
  CRONOS: {
    chainId: "0x19",
    chainName: "Cronos",
    nativeCurrency: { name: "Cronos", symbol: "CRO", decimals: 18 },
    rpcUrls: ["https://cronos.drpc.org", "https://cronos.blockpi.network/v1/rpc/public"],
  },
  FUSE: {
    chainId: "0x7a",
    chainName: "Fuse",
    nativeCurrency: { name: "Fuse", symbol: "FUSE", decimals: 18 },
    rpcUrls: ["https://rpc.fuse.io", "https://fuse.drpc.org", "https://fuse-mainnet.chainstacklabs.com"],
  },
  KAIA: {
    chainId: "0x2019",
    chainName: "Kaia",
    nativeCurrency: { name: "Kaia", symbol: "KAIA", decimals: 18 },
    rpcUrls: ["https://public-en.node.kaia.io", "https://kaia.blockpi.network/v1/rpc/public", "https://klaytn.api.onfinality.io/public", "https://klaytn.drpc.org"],
  },
  MOONBEAM: {
    chainId: "0x504",
    chainName: "Moonbeam",
    nativeCurrency: { name: "Glimmer", symbol: "GLMR", decimals: 18 },
    rpcUrls: ["https://rpc.api.moonbeam.network", "https://moonbeam.drpc.org", "https://1rpc.io/glmr", "https://moonbeam.public.blastapi.io"],
  },
  MOONRIVER: {
    chainId: "0x505",
    chainName: "Moonriver",
    nativeCurrency: { name: "Moonriver", symbol: "MOVR", decimals: 18 },
    rpcUrls: ["https://rpc.api.moonriver.moonbeam.network", "https://moonriver.drpc.org"],
  },
  ASTAR: {
    chainId: "0x250",
    chainName: "Astar",
    nativeCurrency: { name: "Astar", symbol: "ASTR", decimals: 18 },
    rpcUrls: ["https://evm.astar.network", "https://astar.public.blastapi.io", "https://astar.api.onfinality.io/public"],
  },
  AURORA: {
    chainId: "0x4e454152",
    chainName: "Aurora",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.aurora.dev", "https://1rpc.io/aurora", "https://aurora.drpc.org"],
  },
  METIS: {
    chainId: "0x440",
    chainName: "Metis",
    nativeCurrency: { name: "Metis", symbol: "METIS", decimals: 18 },
    rpcUrls: ["https://andromeda.metis.io/?owner=1088", "https://metis-rpc.publicnode.com", "https://metis.drpc.org"],
  },
  BOBA: {
    chainId: "0x120",
    chainName: "Boba",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.boba.network", "https://1rpc.io/boba/eth", "https://gateway.tenderly.co/public/boba-ethereum"],
  },
  ROOTSTOCK: {
    chainId: "0x1e",
    chainName: "Rootstock",
    nativeCurrency: { name: "Rootstock Bitcoin", symbol: "RBTC", decimals: 18 },
    rpcUrls: ["https://public-node.rsk.co", "https://rsk.drpc.org", "https://rpc.ankr.com/rsk"],
  },
  PULSECHAIN: {
    chainId: "0x171",
    chainName: "PulseChain",
    nativeCurrency: { name: "Pulse", symbol: "PLS", decimals: 18 },
    rpcUrls: ["https://rpc.pulsechain.com", "https://pulsechain-rpc.publicnode.com", "https://rpc-pulsechain.g4mm4.io"],
  },
  KCC: {
    chainId: "0x141",
    chainName: "KCC",
    nativeCurrency: { name: "KuCoin Token", symbol: "KCS", decimals: 18 },
    rpcUrls: ["https://rpc-mainnet.kcc.network", "https://kcc.drpc.org", "https://kcc-rpc.com"],
  },
  CORE: {
    chainId: "0x45c",
    chainName: "Core",
    nativeCurrency: { name: "Core", symbol: "CORE", decimals: 18 },
    rpcUrls: ["https://rpc.coredao.org", "https://rpc.ankr.com/core", "https://1rpc.io/core", "https://core.drpc.org", "https://rpcar.coredao.org"],
  },
  FLARE: {
    chainId: "0xe",
    chainName: "Flare",
    nativeCurrency: { name: "Flare", symbol: "FLR", decimals: 18 },
    rpcUrls: ["https://flare-api.flare.network/ext/C/rpc", "https://rpc.ankr.com/flare", "https://flare.rpc.thirdweb.com", "https://rpc.au.cc/flare"],
  },
  X_LAYER: {
    chainId: "0xc4",
    chainName: "X Layer",
    nativeCurrency: { name: "OKB", symbol: "OKB", decimals: 18 },
    rpcUrls: ["https://rpc.xlayer.tech", "https://xlayerrpc.okx.com", "https://xlayer.drpc.org"],
  },
  SHIBARIUM: {
    chainId: "0x6d",
    chainName: "Shibarium",
    nativeCurrency: { name: "Bone ShibaSwap", symbol: "BONE", decimals: 18 },
    rpcUrls: ["https://shibarium.drpc.org", "https://rpc.shibarium.shib.io"],
  },
  DEGEN: {
    chainId: "0x27bc86aa",
    chainName: "Degen",
    nativeCurrency: { name: "Degen", symbol: "DEGEN", decimals: 18 },
    rpcUrls: ["https://rpc.degen.tips", "https://degen.drpc.org", "https://666666666.rpc.thirdweb.com"],
  },
  BEAM: {
    chainId: "0x10f1",
    chainName: "Beam",
    nativeCurrency: { name: "Beam", symbol: "BEAM", decimals: 18 },
    rpcUrls: ["https://build.onbeam.com/rpc", "https://subnets.avax.network/beam/mainnet/rpc", "https://4337.rpc.thirdweb.com"],
  },
  RONIN: {
    chainId: "0x7e4",
    chainName: "Ronin",
    nativeCurrency: { name: "Ronin", symbol: "RON", decimals: 18 },
    rpcUrls: ["https://api.roninchain.com/rpc", "https://ronin.drpc.org", "https://ronin.lgns.net/rpc"],
  },
  OPBNB: {
    chainId: "0xcc",
    chainName: "opBNB",
    nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
    rpcUrls: ["https://opbnb-mainnet-rpc.bnbchain.org", "https://opbnb.drpc.org", "https://opbnb-rpc.publicnode.com", "https://1rpc.io/opbnb"],
  },
  GRAVITY: {
    chainId: "0x659",
    chainName: "Gravity",
    nativeCurrency: { name: "Gravity", symbol: "G", decimals: 18 },
    rpcUrls: ["https://rpc.gravity.xyz", "https://1625.rpc.thirdweb.com"],
  },
  MERLIN: {
    chainId: "0x1068",
    chainName: "Merlin",
    nativeCurrency: { name: "Bitcoin", symbol: "BTC", decimals: 18 },
    rpcUrls: ["https://rpc.merlinchain.io", "https://merlin.drpc.org", "https://4200.rpc.thirdweb.com/"],
  },
  MANTA_PACIFIC: {
    chainId: "0xa9",
    chainName: "Manta Pacific",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://pacific-rpc.manta.network/http", "https://manta-pacific.drpc.org", "https://1rpc.io/manta", "https://manta.nirvana.build", "https://169.rpc.thirdweb.com"],
  },
  TAIKO_ALETHIA: {
    chainId: "0x28c58",
    chainName: "Taiko Alethia",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.mainnet.taiko.xyz", "https://taiko.drpc.org"],
  },
  PLASMA: {
    chainId: "0x2611",
    chainName: "Plasma",
    nativeCurrency: { name: "Plasma", symbol: "XPL", decimals: 18 },
    rpcUrls: ["https://rpc.plasma.to", "https://plasma.drpc.org", "https://9745.rpc.thirdweb.com", "https://plasma.gateway.tenderly.co", "https://plasma-mainnet.gateway.tatum.io"],
  },
  HASHKEY: {
    chainId: "0xb1",
    chainName: "HashKey",
    nativeCurrency: { name: "HashKey Token", symbol: "HSK", decimals: 18 },
    rpcUrls: ["https://mainnet.hsk.xyz", "https://hashkey.drpc.org", "https://rpc.hashkey.hsk.xyz", "https://hashkeychain-mainnet.alt.technology"],
  },
  HEMI: {
    chainId: "0xa867",
    chainName: "Hemi",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.hemi.network/rpc", "https://hemi.drpc.org"],
  },
  HYPEREVM: {
    chainId: "0x3e7",
    chainName: "HyperEVM",
    nativeCurrency: { name: "Hyperliquid", symbol: "HYPE", decimals: 18 },
    rpcUrls: ["https://rpc.hyperliquid.xyz/evm", "https://1rpc.io/hyperliquid", "https://hyperliquid.drpc.org", "https://rpc.hypurrscan.io"],
  },
  IMMUTABLE: {
    chainId: "0x343b",
    chainName: "Immutable zkEVM",
    nativeCurrency: { name: "Immutable X", symbol: "IMX", decimals: 18 },
    rpcUrls: ["https://rpc.immutable.com", "https://immutable-zkevm.drpc.org", "https://immutable.gateway.tenderly.co"],
  },
  MORPH: {
    chainId: "0xb02",
    chainName: "Morph",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.morphl2.io", "https://morph.drpc.org", "https://rpc.ankr.com/morph"],
  },
  MEZO: {
    chainId: "0x7b7c",
    chainName: "Mezo",
    nativeCurrency: { name: "Bitcoin", symbol: "BTC", decimals: 18 },
    rpcUrls: ["https://rpc-http.mezo.boar.network", "https://mainnet.mezo.public.validationcloud.io", "https://mezo.drpc.org", "https://rpc_evm-mezo.imperator.co"],
  },
  REYA: {
    chainId: "0x6c1",
    chainName: "Reya Network",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.reya.network", "https://reya.drpc.org", "https://1729.rpc.thirdweb.com", "https://rpc.reya-cronos.gelato.digital"],
  },
  SWELLCHAIN: {
    chainId: "0x783",
    chainName: "Swell Chain",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://swell.drpc.org", "https://rpc.ankr.com/swell", "https://swell-mainnet.alt.technology", "https://swell.hypersync.xyz", "https://swellchain.gateway.tenderly.co"],
  },
  SWAN: {
    chainId: "0xfe",
    chainName: "Swan",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet-rpc.swanchain.org", "https://mainnet-rpc-01.swanchain.org", "https://mainnet-rpc-02.swanchain.org"],
  },
  VANA: {
    chainId: "0x5c8",
    chainName: "Vana",
    nativeCurrency: { name: "Vana", symbol: "VANA", decimals: 18 },
    rpcUrls: ["https://rpc.vana.org/"],
  },
  STORY: {
    chainId: "0x5ea",
    chainName: "Story",
    nativeCurrency: { name: "Story IP", symbol: "IP", decimals: 18 },
    rpcUrls: ["https://mainnet.storyrpc.io", "https://story.drpc.org", "https://rpc.ankr.com/story", "https://story-mainnet-evmrpc.mandragora.io"],
  },
  INTUITION: {
    chainId: "0x483",
    chainName: "Intuition",
    nativeCurrency: { name: "Trust", symbol: "TRUST", decimals: 18 },
    rpcUrls: ["https://rpc.intuition.systems"],
  },
  ETHERLINK: {
    chainId: "0xa729",
    chainName: "Etherlink",
    nativeCurrency: { name: "Tezos", symbol: "XTZ", decimals: 18 },
    rpcUrls: ["https://node.mainnet.etherlink.com", "https://rpc.ankr.com/etherlink_mainnet"],
  },
  PLUME: {
    chainId: "0x18232",
    chainName: "Plume",
    nativeCurrency: { name: "Plume", symbol: "PLUME", decimals: 18 },
    rpcUrls: ["https://rpc.plume.org", "https://plume.drpc.org", "https://plume-mainnet.gateway.tatum.io"],
  },
  POLYNOMIAL: {
    chainId: "0x1f48",
    chainName: "Polynomial",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.polynomial.fi", "https://rpc-proxy.polynomial.fi"],
  },
  SUPERPOSITION: {
    chainId: "0xd7cc",
    chainName: "Superposition",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.superposition.so", "https://55244.rpc.thirdweb.com"],
  },
  SYNDICATE_COMMONS: {
    chainId: "0x7c833",
    chainName: "Syndicate Commons",
    nativeCurrency: { name: "Syndicate", symbol: "SYND", decimals: 18 },
    rpcUrls: ["https://commons.rpc.syndicate.io", "https://510003.rpc.thirdweb.com", "https://rpc.commons.syndicate.io"],
  },
  SOMNIA: {
    chainId: "0x13a7",
    chainName: "Somnia",
    nativeCurrency: { name: "Somnia Token", symbol: "SOMI", decimals: 18 },
    rpcUrls: ["https://somnia-rpc.publicnode.com", "https://somnia.publicnode.com", "https://api.infra.mainnet.somnia.network", "https://5031.rpc.thirdweb.com"],
  },
  MONAD: {
    chainId: "0x8f",
    chainName: "Monad",
    nativeCurrency: { name: "Monad", symbol: "MON", decimals: 18 },
    rpcUrls: ["https://rpc.monad.xyz", "https://rpc1.monad.xyz", "https://rpc3.monad.xyz", "https://rpc-mainnet.monadinfra.com"],
  },
  MEGAETH: {
    chainId: "0x10e6",
    chainName: "MegaETH",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://mainnet.megaeth.com/rpc", "https://megaeth.drpc.org", "https://rpc-megaeth-mainnet.globalstake.io"],
  },
  MATCHAIN: {
    chainId: "0x2ba",
    chainName: "Matchain",
    nativeCurrency: { name: "BNB", symbol: "BNB", decimals: 18 },
    rpcUrls: ["https://rpc.matchain.io", "https://rpc.ankr.com/matchain_mainnet", "https://698.rpc.thirdweb.com"],
  },
  RACE: {
    chainId: "0x1a95",
    chainName: "RACE",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://racemainnet.io", "https://6805.rpc.thirdweb.com"],
  },
  DOMA: {
    chainId: "0x17cc5",
    chainName: "Doma",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://doma.drpc.org", "https://rpc.doma.xyz"],
  },
  B2: {
    chainId: "0xdf",
    chainName: "B2",
    nativeCurrency: { name: "Bitcoin", symbol: "BTC", decimals: 18 },
    rpcUrls: ["https://rpc.bsquared.network", "https://b2-mainnet.alt.technology"],
  },
  BOTANIX: {
    chainId: "0xe35",
    chainName: "Botanix",
    nativeCurrency: { name: "Bitcoin", symbol: "BTC", decimals: 18 },
    rpcUrls: ["https://rpc.botanixlabs.com"],
  },
  KATANA: {
    chainId: "0xb67d2",
    chainName: "Katana",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.katana.network/", "https://katana.drpc.org/", "https://katana.gateway.tenderly.co", "https://747474.rpc.thirdweb.com/"],
  },
  LENS: {
    chainId: "0xe8",
    chainName: "Lens",
    nativeCurrency: { name: "GHO", symbol: "GHO", decimals: 18 },
    rpcUrls: ["https://rpc.lens.xyz", "https://lens.drpc.org", "https://232.rpc.thirdweb.com"],
  },
  MIND: {
    chainId: "0xe4",
    chainName: "Mind Network",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc-mainnet.mindnetwork.xyz", "https://228.rpc.thirdweb.com"],
  },
  ZERO: {
    chainId: "0x849ea",
    chainName: "ZERO Network",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.zerion.io/v1/zero", "https://543210.rpc.thirdweb.com"],
  },
  ZETACHAIN: {
    chainId: "0x1b58",
    chainName: "ZetaChain",
    nativeCurrency: { name: "Zeta", symbol: "ZETA", decimals: 18 },
    rpcUrls: ["https://zetachain-evm.blockpi.network/v1/rpc/public", "https://zeta-chain.drpc.org"],
  },
  ZKLINKNOVA: {
    chainId: "0xc5cc4",
    chainName: "zkLink Nova",
    nativeCurrency: { name: "Ethereum", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://810180.rpc.thirdweb.com", "https://zklink-nova.api.pocket.network/", "https://rpc.zklink.io"],
  },
  DBK_CHAIN: {
    chainId: "0x134d8db",
    chainName: "DBK Chain",
    nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
    rpcUrls: ["https://rpc.mainnet.dbkchain.io/", "https://20240603.rpc.thirdweb.com/"],
  },
  GEB: {
    chainId: "0x2ced",
    chainName: "GEB",
    nativeCurrency: { name: "Bitcoin", symbol: "BTC", decimals: 18 },
    rpcUrls: ["https://rpc-mainnet-1.bevm.io", "https://rpc-mainnet-2.bevm.io"],
  },
  BITLAYER: {
    chainId: "0x310c5",
    chainName: "Bitlayer",
    nativeCurrency: { name: "Bitcoin", symbol: "BTC", decimals: 18 },
    rpcUrls: ["https://rpc.bitlayer.org", "https://rpc.bitlayer-rpc.com", "https://rpc.ankr.com/bitlayer"],
  },
  CORN: {
    chainId: "0x1406f40",
    chainName: "Corn",
    nativeCurrency: { name: "BTCN", symbol: "BTCN", decimals: 18 },
    rpcUrls: ["https://corn.drpc.org", "https://maizenet-rpc.usecorn.com"],
  },
  FLOW: {
    chainId: "0x2eb",
    chainName: "Flow EVM",
    nativeCurrency: { name: "Flow", symbol: "FLOW", decimals: 18 },
    rpcUrls: ["https://mainnet.evm.nodes.onflow.org", "https://flow-mainnet.gateway.tatum.io"],
  },
};

/** Numeric chainIds we support, derived from DEPLOY_CHAIN_PARAMS keys. */
export const SUPPORTED_CHAIN_IDS: Set<number> = new Set([
  8453, // BASE
  1, // ETHEREUM
  42161, // ARBITRUM_ONE
  10, // OPTIMISM
  137, // POLYGON
  56, // BSC
  43114, // AVALANCHE
  100, // GNOSIS
  324, // ZKSYNC_ERA
  534352, // SCROLL
  59144, // LINEA
  5000, // MANTLE
  81457, // BLAST
  146, // SONIC
  42220, // CELO
  252, // FRAXTAL
  480, // WORLDCHAIN
  130, // UNICHAIN
  80094, // BERACHAIN
  57073, // INK
  2741, // ABSTRACT
  1868, // SONEIUM
  1101, // POLYGON_ZKEVM
  42170, // ARBITRUM_NOVA
  7777777, // ZORA
  34443, // MODE
  1329, // SEI
  5330, // SUPERSEED
  360, // SHAPE
  888888888, // ANCIENT8
  60808, // BOB
  1135, // LISK
  1750, // METAL_L2
  690, // REDSTONE
  466, // APPCHAIN
  484, // CAMP
  5545, // DUCKCHAIN
  7560, // CYBER
  1380012617, // RARI
  48900, // ZIRCUIT
  1612, // OPENLEDGER
  988, // STABLE
  239, // TAC
  124816, // MITOSIS
  8333, // B3
  4114, // CITREA
  25, // CRONOS
  122, // FUSE
  8217, // KAIA
  1284, // MOONBEAM
  1285, // MOONRIVER
  592, // ASTAR
  1313161554, // AURORA
  1088, // METIS
  288, // BOBA
  30, // ROOTSTOCK
  369, // PULSECHAIN
  321, // KCC
  1116, // CORE
  14, // FLARE
  196, // X_LAYER
  109, // SHIBARIUM
  666666666, // DEGEN
  4337, // BEAM
  2020, // RONIN
  204, // OPBNB
  1625, // GRAVITY
  4200, // MERLIN
  169, // MANTA_PACIFIC
  167000, // TAIKO_ALETHIA
  9745, // PLASMA
  177, // HASHKEY
  43111, // HEMI
  999, // HYPEREVM
  13371, // IMMUTABLE
  2818, // MORPH
  31612, // MEZO
  1729, // REYA
  1923, // SWELLCHAIN
  254, // SWAN
  1480, // VANA
  1514, // STORY
  1155, // INTUITION
  42793, // ETHERLINK
  98866, // PLUME
  8008, // POLYNOMIAL
  55244, // SUPERPOSITION
  510003, // SYNDICATE_COMMONS
  5031, // SOMNIA
  143, // MONAD
  4326, // MEGAETH
  698, // MATCHAIN
  6805, // RACE
  97477, // DOMA
  223, // B2
  3637, // BOTANIX
  747474, // KATANA
  232, // LENS
  228, // MIND
  543210, // ZERO
  7000, // ZETACHAIN
  810180, // ZKLINKNOVA
  20240603, // DBK_CHAIN
  11501, // GEB
  200901, // BITLAYER
  21000000, // CORN
  747, // FLOW
]);
