// Brand domain per Bitpanda stock/ETF ticker. Logos are served by DuckDuckGo's
// icon service (icons.duckduckgo.com/ip3/<domain>.ico) which is free, keyless
// and reliable. Clearbit's logo API was deprecated (DNS no longer resolves).
// Includes Bitpanda alias tickers (e.g. FB, *-US, BRKB, TSFA) and receipts
// (SSU/SMSN = Samsung) so every holding gets a logo.
const STOCK_LOGO_DOMAINS: Record<string, string> = {
  // US large caps
  AAPL: "apple.com",
  ABBV: "abbvie.com",
  ACN: "accenture.com",
  ADBE: "adobe.com",
  "AMD-US": "amd.com",
  AMD: "amd.com",
  AMZN: "amazon.com",
  AVGO: "broadcom.com",
  BABA: "alibaba.com",
  BAC: "bankofamerica.com",
  "BRK.B": "berkshirehathaway.com",
  "BRK-B": "berkshirehathaway.com",
  BRKB: "berkshirehathaway.com",
  BROA: "broadcom.com",
  COST: "costco.com",
  CRM: "salesforce.com",
  CVX: "chevron.com",
  FB: "meta.com",
  META: "meta.com",
  GOOGL: "abc.xyz",
  GOOG: "abc.xyz",
  HD: "homedepot.com",
  JNJ: "jnj.com",
  JPM: "jpmorganchase.com",
  "JPM-US": "jpmorganchase.com",
  KO: "coca-cola.com",
  LLY: "lilly.com",
  "LLYC-US": "lilly.com",
  MA: "mastercard.com",
  MRKUS: "merck.com",
  MSFT: "microsoft.com",
  MU: "micron.com",
  NFLX: "netflix.com",
  NVDA: "nvidia.com",
  ORCL: "oracle.com",
  PEP: "pepsico.com",
  PG: "pg.com",
  PLTR: "palantir.com",
  TSLA: "tesla.com",
  UNH: "unitedhealthgroup.com",
  WMT: "walmart.com",
  "WMT-US": "walmart.com",
  XOM: "exxonmobil.com",
  // Asia
  HYXS: "skhynix.com",
  SSU: "samsung.com",
  SMSN: "samsung.com",
  TCTZF: "tencent.com",
  TM: "toyota.com",
  TSFA: "tsmc.com",
  TSM: "tsmc.com",
  // Europe
  ADS: "adidas-group.com",
  AIR: "airbus.com",
  ALV: "allianz.com",
  ASML: "asml.com",
  BAS: "basf.com",
  BAYN: "bayer.com",
  BMW: "bmwgroup.com",
  CBK: "commerzbank.com",
  DBK: "db.com",
  DTE: "telekom.com",
  HEN3: "henkel.com",
  IBE: "iberdrola.com",
  IFX: "infineon.com",
  MC: "lvmh.com",
  NESN: "nestle.com",
  NOVN: "novartis.com",
  NOVO: "novonordisk.com",
  OR: "loreal.com",
  RDSA: "shell.com",
  RHM: "rheinmetall.com",
  RMS: "hermes.com",
  ROG: "roche.com",
  SAN: "santander.com",
  SAP: "sap.com",
  SHEL: "shell.com",
  SIE: "siemens.com",
  SPCX: "spacex.com",
  VOW3: "volkswagen-group.com",
  // ETFs
  EUNL: "ishares.com",
  IS3N: "ishares.com",
  QDVE: "ishares.com",
  SXR8: "ishares.com",
  VUSA: "vanguard.co.uk",
  VWCE: "vanguard.co.uk",
  VWRL: "vanguard.co.uk",
};

export function getCexStockLogoUrl(symbol: string): string | null {
  const key = symbol.trim().toUpperCase();
  const domain = STOCK_LOGO_DOMAINS[key];
  return domain ? `https://icons.duckduckgo.com/ip3/${domain}.ico` : null;
}
