export const DEFAULT_CHAINS = [
  "BASE", "ETHEREUM", "ARBITRUM_ONE", "OPTIMISM", "POLYGON",
  "BSC", "AVALANCHE", "GNOSIS", "ZKSYNC_ERA", "LINEA",
  "SOLANA", "COSMOS_HUB", "ZERO", "INJECTIVE", "SCROLL", "TON",
];
