const EXPLORERS: Record<string, string> = {
  ethereum: "https://etherscan.io",
  base: "https://basescan.org",
  arbitrum_one: "https://arbiscan.io",
  optimism: "https://optimistic.etherscan.io",
  polygon: "https://polygonscan.com",
  bsc: "https://bscscan.com",
  avalanche: "https://snowtrace.io",
  gnosis: "https://gnosisscan.io",
  zksync_era: "https://era.zksync.network",
  linea: "https://lineascan.build",
  solana: "https://solscan.io",
  polygon_zkevm: "https://zkevm.polygonscan.com",
  scroll: "https://scrollscan.com",
  mantle: "https://mantlescan.xyz",
  mode: "https://modescan.io",
  blast: "https://blastscan.io",
  celo: "https://celoscan.io",
  fraxtal: "https://fraxscan.com",
  zora: "https://zorascan.xyz",
  worldchain: "https://worldscan.org",
  robinhood_chain: "https://robinhoodchain.blockscout.com",
  unichain: "https://uniscan.xyz",
  ink: "https://inkscan.xyz",
  soneium: "https://soneium.blockscout.com",
  abstract: "https://abstractscan.xyz",
  berachain: "https://berascan.com",
  monad: "https://monadexplorer.com",
  sei: "https://seistream.app",
  shape: "https://shapescan.xyz",
  sonic: "https://sonicscan.org",
  corn: "https://cornscan.io",
  ape: "https://apescan.io",
  metis: "https://metis-explorer.io",
  moonbeam: "https://moonscan.io",
  moonriver: "https://moonriver.moonscan.io",
  cronos: "https://cronoscan.com",
  aurora: "https://aurorascan.dev",
  boba: "https://bobascan.com",
  fuse: "https://explorer.fuse.io",
  astar: "https://astar.subscan.io",
  rootstock: "https://rootstock.blockscout.com",
  core: "https://scan.coredao.org",
  flare: "https://flare-explorer.flare.network",
  x_layer: "https://www.okx.com/explorer/xlayer",
  shibarium: "https://shibariumscan.io",
  degen: "https://explorer.degen.tips",
  beam: "https://subnets.avax.network/beam",
  ronin: "https://app.roninchain.com",
  opbnb: "https://opbnbscan.com",
  lisk: "https://blockscout.lisk.com",
  cyber: "https://cyberscan.co",
  openledger: "https://scan.openledger.xyz",
  tac: "https://explorer.tac.build",
  citrea: "https://explorer.mainnet.citrea.xyz",
  mitosis: "https://explorer.mitosis.org",
  b3: "https://explorer.b3.fun",
  appchain: "https://explorer.appchain.xyz",
  duckchain: "https://explorer.duckchain.io",
  zircuit: "https://explorer.zircuit.com",
  stable: "https://explorer.stable.xyz",
  redstone: "https://explorer.redstone.xyz",
  ancient8: "https://scan.ancient8.gg",
  bob: "https://explorer.gobob.xyz",
  superseed: "https://explorer.superseed.xyz",
  metal_l2: "https://explorer.metall2.com",
  camp: "https://explorer.campnetwork.xyz",
  gravity: "https://explorer.gravity.xyz",
  merlin: "https://scan.merlinchain.io",
  manta_pacific: "https://pacific-explorer.manta.network",
  taiko_alethia: "https://taikoscan.io",
  plasma: "https://plasmascan.to",
  hashkey: "https://explorer.hsk.xyz",
  hemi: "https://explorer.hemi.xyz",
  hyperevm: "https://hyperevmscan.io",
  immutable: "https://explorer.immutable.com",
  morph: "https://explorer.morph.network",
  mezo: "https://explorer.mezo.org",
  reya: "https://explorer.reya.network",
  swellchain: "https://explorer.swellnetwork.io",
  swan: "https://mainnet-explorer.swanchain.io",
  vana: "https://vanascan.io",
  story: "https://www.storyscan.io",
};

export function getExplorerUrl(chainKey: string, contract: string): string | null {
  const key = chainKey.toLowerCase();
  const base = EXPLORERS[key];
  if (base) {
    if (key === "solana") return `${base}/account/${contract}`;
    if (key === "sei") return `${base}/contracts/${contract}`;
    return `${base}/address/${contract}`;
  }
  // No known explorer — return null rather than a broken testnet link
  return null;
}
